# Generated by Django 3.2.7 on 2021-11-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_privatedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatedocument',
            name='uploadedFile',
            field=models.FileField(upload_to='equiposv1/static/img/'),
        ),
    ]
