# Generated by Django 3.2.7 on 2021-11-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_privatedocument_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatedocument',
            name='uploadedFile',
            field=models.FileField(upload_to='static/img/'),
        ),
    ]
