# Generated by Django 3.2.7 on 2021-12-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0002_delete_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_id', models.IntegerField()),
                ('evento_descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
